### ISSUE TITLE
Undefined method mysqli_stmt::get_result()

### ISSUE THREAD

**Issue by jerry1970** [tomyvi/owntracks-php-client#19]
I get this error: `Call to undefined method mysqli_stmt::get_result()`.
Here:
https://stackoverflow.com/questions/8321096/call-to-undefined-method-mysqli-stmtget-result
I read I miss a driver but cannot install drivers on my web host.

But isn't it easier to use PDO?

**Comment by tomyvi** [comment]
MySQL PDO implemented
