### ISSUE TITLE
I only receive "HTTP status 200: JsonParseException" in OwnTracks app

### ISSUE THREAD

**Issue by FilmTraveler** [tomyvi/owntracks-php-client#25]
Hello. I configured php-tracks-recorder on my server, set up the database, and the front-end is working nicely (with a blank map since there's no data yet). However, no data is making it through. In OwnTracks, I have it configured to use HTTP connection, and it is set to be (obviously an example) "http://www.myserver.com/mydirectory/record.php" (with nothing entered under "Identification").

Under "Status," however, I get "HTTP status 200: JsonParseException" as the Endpoint Status Message. ("Idle" is the Endpoint state. in case that matters.)

At some point in the future, I hope to enable HTTPS and boost security, but for now I just want to troubleshoot and get it working, and I can't even get any data posted. What am I doing wrong?

**Comment by schnudeldudel** [comment]
Hi,

I also get the same response in the. Owntracks App (Android) and it works fine.

Do you use MySQL and if so, did you check if data is written to the database (phpmyadmin maybe helpful here to have a nice webfrontend for mysql database Management...)

Cheers.

**Comment by tbolick** [comment]
I just spent an hour tracking this down and it turned out my DB user did not have access to that database.
