### ISSUE TITLE
Add TID to popup

### ISSUE THREAD

**Issue by danmed** [tomyvi/owntracks-php-client#6]
Would it be possible to add the TID to the Marker popup?

I have it tracking 3 phones and i'd like to know which one is which :)

**Comment by tomyvi** [comment]
Multi user mapping is definitively on the roadmap, stay tuned !

**Comment by jmhunter** [comment]
Anything I can do to help with multi-user support? Perhaps we can open a new issue to discuss what needs doing there?

**Comment by tomyvi** [comment]
now redundant with #9

**Comment by tomyvi** [comment]
New features ready to be tested in dev branch. Please let me know @jmhunter @danmed
